# Generated by Django 3.1.5 on 2022-01-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('item', models.CharField(max_length=200)),
                ('place', models.CharField(blank=True, choices=[('Fridge', 'Fridge'), ('Freezer', 'Freezer'), ('Pantry', 'Pantry')], max_length=30)),
            ],
        ),
    ]
